# Generated by Django 2.2.10 on 2022-02-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excepciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True)),
                ('modulo', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'permissions': (('can_see_excepciones', 'can see excepciones'),),
            },
        ),
    ]
