# Generated by Django 2.2.10 on 2022-01-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover',
            field=models.ImageField(default='album/default.png', upload_to='album/'),
        ),
    ]
