# Generated by Django 2.2.10 on 2022-01-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('nickName', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'artista',
            },
        ),
    ]
