# Generated by Django 2.2.10 on 2022-01-19 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('name_album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_album', to='album.Album')),
            ],
            options={
                'db_table': 'track',
            },
        ),
    ]
