# Generated by Django 2.2.10 on 2022-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='name_album',
            new_name='album',
        ),
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(null=True, upload_to='track/'),
        ),
    ]
